### ISSUE TITLE
Game crash "A fatal error ..."

### ISSUE THREAD

**Issue by CodePilot58** [UQdeco2800/2021-studio-1#113]
# **Description**
After a seemingly random amount of time, the game will crash and print an error similar to the one given below:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000006e9cbbb1, pid=1752, tid=4340
#
# JRE version: OpenJDK Runtime Environment (11.0+28) (build 11+28)
# Java VM: OpenJDK 64-Bit Server VM (11+28, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [gdx-box2d64.dll+0xbbb1]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\...\2021-studio-1\source\core\assets\hs_err_pid1752.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed
```

# **Hypothesis**
It is linked to spawning in new entities as it always occurs when the player passes the `LoadLevelTrigger` which loads a new level when the player collides with it. This can be observed by enabling debug mode in the game or by enabling logging for `AreaManager` and seeing that the game reports it is starting to load another level just before a crash.

Inside the error report file, the following line always exists:
```
Usage:
  Non-class:     18.23 MB capacity,    18.06 MB (>99%) used,   144.26 KB ( <1%) free+waste,    35.06 KB ( <1%) overhead. 
      Class:      1.73 MB capacity,     1.62 MB ( 94%) used,    98.48 KB (  6%) free+waste,    14.19 KB ( <1%) overhead. 
       Both:     19.96 MB capacity,    19.67 MB ( 99%) used,   242.74 KB (  1%) free+waste,    49.25 KB ( <1%) overhead. 
```
As well as some form of this line:
```
siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0x0000003600000002
```

This gives an indication that the game is running out of memory for some function and then trying to read memory it has no access to. Also in the error report is the stack trace, labelling the following function as the culprit:
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.badlogic.gdx.physics.box2d.World.jniCreateBody(JIFFFFFFFFZZZZZF)J+0
j  com.badlogic.gdx.physics.box2d.World.createBody(Lcom/badlogic/gdx/physics/box2d/BodyDef;)Lcom/badlogic/gdx/physics/box2d/Body;+80
```
This function can be seen at [World.java](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/World.java) in the LibGDX library. It shows that it is the function behind creating physics bodies, and it is private so we can't see what exactly it does.

Here is what I think the possible problems are:

1. The game is running out of space for the entities, i.e. we are creating too many
2. The game cannot handle creating lots of entities in a single update
3. There is something about the way we load worlds that make us prone to this issue

## Arguments against each hypothesis
1. I have previously enabled logging for the `EntityService` and have seen upwards of 1000 entities registered with the `EntityService` without crashing, but then this crash can also occur when there is <200 entities registered. However, this does not count every entity implementing the `ColliderComponent` or `PhysicsComponent`, which may have its own entity limit.
2. The game has no issue creating the world after clicking 'run' on the main screen, and the crashes seem random, linked to no particular level to be loaded (this was tested by logging which level was being loaded before a crash, and there was no pattern seen)
3. This is the most likely and is the real cause of hypothesis 1 and 2, but also hard to diagnose. Something that goes against this, is it is not always the same body creation that causes a crash; sometimes it is `createFloor()`, sometimes `spawnWolf()`, not reliably the same method.

# **Answer**
Tutor _Jack Emerson_ predicted that this bug was from improper entity disposal, he was right.

`EntityService.disposeAfterStep(Entity target)` was the culpurit. It was called by the Wall of Death as it passed entities using `TouchDisposeComponent` (basically cleaning up no longer used entities). This fucntion added entities to a list, disposing of them during an update outside of the physics step. Most likely, this was either not disposing of entities properly or causing some entities to be disposed of twice(?).

The offending function was deleted, and entity disposal is now handled by `Entity.flagDelete`. Error no longer occurs as far as I can see. See commit 5feddabffcfe4ec01ab64d5f0648594e3bf7398b for full fix details.

**Comment by neo-take-lucy** [comment]
It isn't *super* random, it occurs after the creation of ~1800-2000 physics bodies and ~950 active ones.

**Comment by CodePilot58** [comment]
Not for me, here is part of the bottom of my last crash:
```
FINE: Finished placing terrain in buffer
    12:34:51:731 com.deco2800.game.areas.AreaManager makeBufferedPlace
FINE: Registering Entity{id=310} in entity service
    12:34:51:732 com.deco2800.game.entities.EntityService register
FINE: Registering Entity{id=311} in entity service
    12:34:51:732 com.deco2800.game.entities.EntityService register
FINE: Registering Entity{id=313} in entity service
    12:34:51:732 com.deco2800.game.entities.EntityService register
#
# A fatal error has been detected by the Java Runtime Environment:
```
Here, only 313 entities have been created in the game so far.

**Comment by neo-take-lucy** [comment]
Overflow areas to consider:
a) Wall of Death still doesn't dispose of anything at or below y = 0. 
b) Each "Floor" is 9 entities spawned together (my fault)

**Comment by neo-take-lucy** [comment]
where abouts did you find the logger files for Entity Service? / about what line number did u find that info on

**Comment by CodePilot58** [comment]
Some of that has been fixed in branch sprint3/team2 where I'm making my changes; 
1. Floors are one entity now
2. wall of death disposes of things at 0 and below. 

This crash now happens at like the third level load for me, wall of death probably hasn't even had the chance to dispose of anything.

**Comment by neo-take-lucy** [comment]
thats funky. can you push your fixes onto main and I'll have a crack at getting some numbers at the very least.

**Comment by CodePilot58** [comment]
In `logging.properties` I added the following line:
```
com.deco2800.game.entities.EntityService.level = FINE
```
Which allows the `EntityService` to prints its `logger.debug` calls to the terminal. That output is copied from my terminal output.

**Comment by CodePilot58** [comment]
I'm just adding some more documentation and then I'll push to main :))

**Comment by neo-take-lucy** [comment]
schweeeeet. send me a msg on slack so i can pull when you do.

**Comment by CodePilot58** [comment]
Bug fixed. Annoyingly, this was caused by a function I created a few weeks ago to do with entity disposal. See original comment for details.
