### ISSUE TITLE
Game Speed 

### ISSUE THREAD

**Issue by WintonNeg** [UQdeco2800/2021-studio-1#39]
# **Description**
**Task:** [Game Speed](#39 ).
**Feature:** [Team 1 - Attack animations, Player collision with entities, Power ups, game speed](#33 )
 
Update the game speed so that it feels more natural and more enjoyable to play.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Sept. 8)
 
**Completion Deadline:** Sept. 14
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Members**

- Winston Niogret (@WintonNeg) (Winton)
- Sean Dolan (@devDolan) (Sean Dolan)
- Lauren Whitehead (@LaurenWhitehead) (Lauren Whitehead)
- Shenhui Zhu (@Shenhui77) (Shenhui Zhu)

**Comment by neo-take-lucy** [comment]
check physcs component lol
