### ISSUE TITLE
Enemy AI logic

### ISSUE THREAD

**Issue by JohnCom** [UQdeco2800/2021-studio-1#52]
### Description

Development of enemy AI that responds to player location, this may be in the form of an enemy path finding algorithm or static responses to perceived player state -- i.e walk left if the player is left etc. 
This could be refinements to existing enemy AI classes or extending them in some fashion.

- [ ] Determine what a useful change to enemy AI logic might be and chat with team 4. 
- [ ] Develop this change as integrated change with existing enemy AI classes. 
- [ ] Test the changes -- significantly.

**Comment by neo-take-lucy** [comment]
team 4 issue maybe?
