### ISSUE TITLE
Team 2 - Map fixes, aesthetic upgrades, Wall of Death speed change

### ISSUE THREAD

**Issue by CodePilot58** [UQdeco2800/2021-studio-1#80]
# **Description**
**Feature:** Team 2 - Map fixes and Aesthetic Upgrades, Wall of Death speed change #80 

This sprint is focused on upgrading what features this team has added so far, fixing some bugs, and wrangling the aesthetic of the game into a more cohesive theme. The primary tasks to be worked on will be fixing/improving collision bugs, loading of levels and improving the textures of the wall of death. This leads to the tasks set out in the milestones.

- **Improve terrain generation** - at the moment there is a bug where the player has a chance to 'collide' with each of the floor or terrain blocks. This is a bug in the game engine but a simple workaround is to make each block of floor or platforms act as a single entity so the player cannot have single interactions with the pieces. We are also going to make the selection of worlds more random with more worlds to choose from to allow for greater variation in the gameplay, and fix the problem of the player remaining alive when they fall through holes in the floor.
- **Make the giant's speed reflect the player's position** - as the player runs away from the giant it quickly becomes a far less threatening entity. To help make the giant more of a problem for the player, the giant's speed will change based on the distance to the player. This will mean the giant will never be far away, and could even get faster as the game progresses.
- **Add new textures to the terrain** - We will be adding two new backgrounds to the game to reflect a couple of the themes, with Team 3 continuing to work on some more. In addition to this, we will create textures for the floor of each world theme and make sure these textures are spawned together with each new level.
- **Tutorial screen** - To help new users understand the game better, we will add a tutorial screen entity which shows at the start of the game, giving basic information like controls and possibly some flavour text for the storyline of the game. 
- **Upgraded wall of death aesthetic** - Improve the death giant's visual themes and animations to better fit with the rest of the game.
- **Testing** - unit testing for each of our coded features and user tests for the aesthetic changes

# **Dependencies**
- We are working with team 3 to finalise all backgrounds #96 

# **Milestones**
List of tasks that need to be completed for this feature.
- [x] #107 - 28 Sept
- [x] #68 - 26 Sept
- [x] #78 - 28 Sept
- [x] #67 - 25 Sept
- [x] #81 - 24 Sept
- [x] #108 - 22 Sept
 
**Completion Deadline:** Oct. 5th
 
# **Documentation**
- [x] #134
- [x] [Tutorial screen](../wiki/Tutorial-Level)
- [x] [Level Loading](../wiki/Loading-rag-files-into-the-game)

# **Changes to plan** 
The game was experiencing a crash arising from native code, meaning it was a total crash with a difficult to decipher log file. This was fixed, with the process given in #113.

The width of the background images has not been correclty implemented yet. In sprint 4 we will investigate to see what the best way to put background images in is, since at the moment they are a entity with the lowest possibly `zIndex` which puts them at the back of the render and the width of the image is hard to control with changing level widths.
 
# **Members**
- Jackson Geritz (@jacksongeritz) (Jackson)
- Xaviour Greenhalgh (@XaviourG) (Xaviour D Greenhalgh)
- Akash Iyer (@akash450) (Akash Iyer)
- Sam Lucena (@CodePilot58) (Sam Lucena)
- Peter Tran (@peter-tr) (Peter Tran)

**Comment by Dr2n** [comment]
Would like to see some milestones and subtasks for this ticket.

**Comment by XaviourG** [comment]
Hurrah
